language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - functions/node_modules
install:
  - cd functions/
  - yarn
  - cd ..
  - yarn
script:
  - yarn ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token: "$FIREBASE_TOKEN"
  on: master
