language: node_js
node_js: '10'
install:
  - cd functions/
  - npm ci
  - cd ..
  - npm ci
jobs:
  include:
    - stage: test front-end
      script: npm run cypress
    - stage: deploy front-end
      script:
        - npm install -g firebase-tools
        - npx firebase-tools deploy --only hosting --token "$FIREBASE_TOKEN"
stages:
  - test front-end
  - name: deploy front-end
    if: branch = master
