language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - functions/node_modules
script:
  - $(npm bin)/cypress run --record
  - yarn build
deploy:
  provider: firebase
  token: "$FIREBASE_TOKEN"
  on: master
