language: node_js
node_js: '8'
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
    - functions/node_modules
install:
  - cd functions/
  - yarn
  - cd ..
  - yarn

jobs:
  include:
    - stage: test front-end
      script: yarn ci
    - stage: deploy front-end
      script:
        - yarn build
        - firebase deploy --only hosting --token "$FIREBASE_TOKEN"

stages:
  - test front-end
  - name: deploy front-end
    if: branch = master
